name: CI/CD Actions

on: # запускать процессы при push и pull_request в ветку main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CI: # здесь буду выполняться проверки линтерами и тесты
    name: Continuous Integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['21.x']
    steps:
      - name: Проверяем код репозитория
        uses: actions/checkout@v4

      - name: Настраиваем Node.js версии ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Устанавливаем зависимости
        run: npm ci
      # Проверки кодстайла
      - name: Проверка Prettier
        run: npm run lint:prettier
      - name: Проверка Eslint
        run: npm run lint:eslint
      # Тесты

  CD: # эта часть отвечает за развёртывание приложения
    name: Continuous Deployment
    needs: CI
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['21.x']
    steps:
      - name: Проверяем код репозитория
        uses: actions/checkout@v4

      - name: Настраиваем Node.js версии ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Устанавливаем зависимости
        run: npm ci

      - name: Создаём build и отправляем его на сайт
        run: |
          git config --global user.email ${{ secrets.MY_EMAIL }}
          git config --global user.name ${{ secrets.MY_NAME }}
          git config --global user.email 
          git config --global user.name

          git remote set-url origin ${{ secrets.MY_ORIGIN_ADDRESS }}
          npm run deploy
