name: CI/CD Actions
run-name: CI/CD Actions in work

on: # запускать процессы при push и pull_request в ветку main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CI: # здесь буду выполняться проверки линтерами и тесты
    name: Continuous Integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['21.x']
    steps:
      - name: Проверяем код репозитория
        uses: actions/checkout@v4

      - name: Настраиваем Node.js версии ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Устанавливаем зависимости
        run: npm ci

      - name: Создаём build
        run: npm run build

      # Проверки кодстайла
      - name: Проверка Prettier
        run: npm run lint:prettier
      - name: Проверка Eslint
        run: npm run lint:eslint

      # Тесты

  CD: # эта часть отвечает за развёртывание приложения
    name: Continuous Deployment
    needs: CI
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['21.x']
    steps:
      - name: Проверяем код репозитория
        uses: actions/checkout@v4

      - name: Настраиваем Node.js версии ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Устанавливаем SSH ключи
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.DEPLOY_SSH_KEY }}" >> "$HOME/.ssh/id_rsa"
          chmod 600 "$HOME/.ssh/id_rsa"

      - name: Устанавливаем зависимости
        run: npm ci

      - name: Создаём build и отправляем его на сервер
        run: |
          npm run deploy
          scp -i $HOME/.ssh/id_rsa -o StrictHostKeyChecking=no -r dist/* ${{ secrets.DEPLOY_SERVER_INFO }}

        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
          VITE_UNSPLASH_BASE_URL: ${{ secrets.VITE_UNSPLASH_BASE_URL }}
          VITE_UNSPLASH_AUTH_KEY: ${{ secrets.VITE_UNSPLASH_AUTH_KEY }}
          VITE_REMOTE_STORE: ${{ secrets.VITE_REMOTE_STORE }}
